name: Create release

on:
  push:
    branches:
      - 'v.**'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/create-release@v1
        with:
          java-version: 8

      - name: Extract branch name
        run: |
        echo "::set-env name=BRANCH_NAME::${GITHUB_REF##*/}"

      - name: Print ENV
        run: |
          printenv

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_REF_SLUG }}
          release_name: Release ${{ env.GITHUB_REF_SLUG }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_REPO_CONFIG_SERVER }}:${{ env.GITHUB_REF_SLUG }} .

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_REPO_CONFIG_SERVER }}:${{ env.GITHUB_REF_SLUG }}

