name: Build and Push to Docker

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'
      - 'master'

jobs:

  build_maven_dev:
    name: Build maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}