name: Build and Push to Docker

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:

  create_image:
    name: Create and push image to docker hub
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_CONFIG_SERVER: zaytsevdv/config-server
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: set ENV
        run:

          if [ "github.ref" == "refs/heads/master" ]; then
          echo "Create PRODUCTION image"
          echo "::set-env name=APP_POLYGON::prod"
          else
          echo "Create DEVELOP image"
          echo "::set-env name=APP_POLYGON::dev"
          fi
      - name: Docker build2
        run: |
          printenv

