name: Build and Push to Docker

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'
      - 'master'

jobs:

  test_task:
    name: TEST TASK NAME
    runs-on: ubuntu-latest
    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/dev')
        run: |
          echo "::set-env name=APP_POLYGON::dev"
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=APP_POLYGON::release"
      - name: Build the docker image from local Dockerfile
        run: docker build -t config-server-${APP_POLYGON}:latest .