name: Build and Push to Docker

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'
      - 'master'

jobs:

  test_task:
    name: TEST TASK NAME
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: set APP_POLYGON
        run: |
          if [[ "github.ref" == "refs/heads/master" ]]; then
             echo "Create PRODUCTION image"
             echo "::set-env name=APP_POLYGON::prod"
          else
          echo "Create DEVELOP image"
          echo "::set-env name=APP_POLYGON::dev"
          fi

      - name: Create and push image
        run: |
          echo "::set-env name=DOCKER_IMAGE_TAG=$APP_POLYGON-${GITHUB_SHA:0:8}"
          echo "Docker image tag is: ${DOCKER_IMAGE_TAG}"





