name: Create release

on:
  push:
    branches:
      - 'v.**'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TAG_NAME: ${{ github.ref#refs/heads/ }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_REPO_CONFIG_SERVER }}:${{ github.ref }} .

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_REPO_CONFIG_SERVER }}:${{ github.ref }}

